### ISSUE TITLE
Use `===` instead of `==`

### ISSUE THREAD

**Issue by gauravdas014** [PalisadoesFoundation/talawa-api#182]
Currently in some sections of code `==` is being used and `===` in some sections. As `==` can create trouble at times, eg: `==` will return true if we compare (null == undefined), therefore, it becomes difficult to debug the code. Moreover, we should be consistent regarding using of the equality operator. So all the `==` should be changed to `===`

@Sagar2366 @Laurell876 can you please assign me this issue?

**Comment by iamsaumya** [comment]
Apologies @gauravdas014, I have already addressed this issue in #125. However, I welcome you to review the changes in the PR and help the team with cross-checking.

**Comment by gauravdas014** [comment]
@iamsaumya that's fine. We are here to contribute, so it does not matter who has contributed, in the end, the project should be bug-free. Pr 125 has introduced changes to 118 files, which is a little difficult to review, still, I will see the changes and will let you know if you missed out on anything.

**Comment by iamsaumya** [comment]
Thank you so much Gaurav 😄  , I really appreciate it!

**Comment by Sagar2366** [comment]
@gauravdas014 closing this issue, if you don't see the changes in master you can reopen it again.
